# Generated by Django 2.2.5 on 2019-12-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_books_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccountprofile',
            name='favourites',
            field=models.ManyToManyField(related_name='favourites', to='mainapp.Books'),
        ),
        migrations.AddField(
            model_name='customeraccountprofile',
            name='haveread',
            field=models.ManyToManyField(related_name='haveread', to='mainapp.Books'),
        ),
        migrations.AddField(
            model_name='customeraccountprofile',
            name='readingnow',
            field=models.ManyToManyField(related_name='readingnow', to='mainapp.Books'),
        ),
        migrations.AddField(
            model_name='customeraccountprofile',
            name='toread',
            field=models.ManyToManyField(related_name='toread', to='mainapp.Books'),
        ),
    ]
