# Generated by Django 2.2.5 on 2020-01-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191231_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccountprofile',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='customeraccountprofile',
            name='haveread',
        ),
        migrations.RemoveField(
            model_name='customeraccountprofile',
            name='readingnow',
        ),
        migrations.RemoveField(
            model_name='customeraccountprofile',
            name='toread',
        ),
        migrations.AddField(
            model_name='books',
            name='favourites',
            field=models.ManyToManyField(default='none', related_name='favourites', to='mainapp.CustomerAccountProfile'),
        ),
        migrations.AddField(
            model_name='books',
            name='haveread',
            field=models.ManyToManyField(default='none', related_name='haveread', to='mainapp.CustomerAccountProfile'),
        ),
        migrations.AddField(
            model_name='books',
            name='readingnow',
            field=models.ManyToManyField(default='none', related_name='readingnow', to='mainapp.CustomerAccountProfile'),
        ),
        migrations.AddField(
            model_name='books',
            name='toread',
            field=models.ManyToManyField(default='none', related_name='toread', to='mainapp.CustomerAccountProfile'),
        ),
    ]
