# Generated by Django 2.2.5 on 2020-01-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200101_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Book')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CustomerAccountProfile')),
            ],
        ),
    ]
