# Generated by Django 2.2.5 on 2020-01-20 19:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_review_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
