# Generated by Django 2.2.5 on 2020-01-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.ManyToManyField(default='none', related_name='dislikes', to='mainapp.CustomerAccountProfile'),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(default='none', related_name='likes', to='mainapp.CustomerAccountProfile'),
        ),
    ]
