# Generated by Django 2.2.5 on 2020-03-04 20:09

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200128_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
