# Generated by Django 2.2.5 on 2020-03-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_metrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics',
            old_name='book_data',
            new_name='metrics_data',
        ),
    ]
